export const bannedKeywords = [
  // Inglês
  "nude",
  "sex",
  "porn",
  "erotic",
  "explicit",
  "child abuse",
  "underage",
  "illegal photos",
  "child porn",
  "rape",
  "incest",
  "pedophilia",
  "adult content",
  "hardcore",
  "fetish",
  "provocative",
  "xxx",
  "nsfw",
  "violence",
  "abuse",
  "sexual assault",
  "harassment",
  "obscene",

  // Português
  "nudez",
  "sexo",
  "pornô",
  "erótico",
  "explícito",
  "abuso infantil",
  "menor de idade",
  "fotos ilegais",
  "pornografia infantil",
  "estupro",
  "incesto",
  "pedofilia",
  "conteúdo adulto",
  "violência",
  "assédio",
  "fetiche",
  "conteúdo explícito",
  "hardcore",
  "obsceno",
  "ataque sexual",
  "abuso sexual",
];
